export { CreateUsersTable } from "./CreateUsersTable"
export { CreatePostsTable } from "./CreatePostsTable"
export { CreateCommentsTable } from "./CreateCommentsTable"
export { CreateTagsTable } from "./CreateTagsTable"
export { CreatePostTagTable } from "./CreatePostTagTable"
export { CreateCategoriesTable } from "./CreateCategoriesTable"
